trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob  
- stage: QADeploy
  jobs:
  - job: QADeployJob1
    steps:
      - bash: echo QA Deploy Job1



