trigger:
- master
# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo 'Do the Build'
- stage: DevDeploy
  jobs:
  - deployment: DevDeploJob
    environment: Dev
    strategy:
       runOnce:
          deploy:
            steps:
              - bash: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeploJob
    environment: QA
    strategy:
       runOnce:
          deploy:
            steps:
              - bash: echo deploy to QAServer

# steps:
# - script: echo running on $(operatingSystem)
#   displayName: 'Run a one-line script'
